// Inventario normativo SERFOR - lote OPR, generado desde: indice_opr.csv
// Coleccion: Lineamientos y Directivas OPR  |  Documentos: 116
// Regenerar con: generar-inventario-opr.ps1
const INVENTARIO = [
  {
    "id": 1,
    "tipo": "Lineamientos",
    "titulo": "Disponen modificación de los Lineamientos para el ejercicio de la potestad sancionadora y desarrollo del procedimiento administrativo sancionador - RDE D0000213-2024-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2024,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2024-09-06",
    "kb": 316.0,
    "archivo": "documentos/opr_01_disponen_modificacion_de_los_lineamientos_para_el_ejerc_resolucion.pdf",
    "original": "01_disponen_modificacion_de_los_lineamientos_para_el_ejerc_resolucion.pdf"
  },
  {
    "id": 2,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprueban los Lineamientos para la elaboración de Declaraciones de Manejo de Fauna Silvestre aplicables a zoocriaderos - RDE D0000224-2024-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2024,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2024-09-18",
    "kb": 367.0,
    "archivo": "documentos/opr_02_aprueban_los_lineamientos_para_la_elaboracion_de_declar_resolucion.pdf",
    "original": "02_aprueban_los_lineamientos_para_la_elaboracion_de_declar_resolucion.pdf"
  },
  {
    "id": 3,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprueban los Lineamientos para la elaboración de Declaraciones de Manejo de Fauna Silvestre aplicables a zoocriaderos - RDE D0000224-2024-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2024,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2024-09-18",
    "kb": 613.0,
    "archivo": "documentos/opr_02_aprueban_los_lineamientos_para_la_elaboracion_de_declar_documento.pdf",
    "original": "02_aprueban_los_lineamientos_para_la_elaboracion_de_declar_documento.pdf"
  },
  {
    "id": 4,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Modifican los Lineamientos para la elaboración de declaración de manejo para permisos de aprovechamiento forestal en Comunidades Nativas y Comunidades Campesinas - RDE D0000209-2024-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2024,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2024-09-05",
    "kb": 415.0,
    "archivo": "documentos/opr_03_modifican_los_lineamientos_para_la_elaboracion_de_decla_resolucion.pdf",
    "original": "03_modifican_los_lineamientos_para_la_elaboracion_de_decla_resolucion.pdf"
  },
  {
    "id": 5,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Modifican los Lineamientos para la elaboración de declaración de manejo para permisos de aprovechamiento forestal en Comunidades Nativas y Comunidades Campesinas - RDE D0000209-2024-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2024,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2024-09-05",
    "kb": 347.0,
    "archivo": "documentos/opr_03_modifican_los_lineamientos_para_la_elaboracion_de_decla_documento.pdf",
    "original": "03_modifican_los_lineamientos_para_la_elaboracion_de_decla_documento.pdf"
  },
  {
    "id": 6,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprobar lo \"Lineamientos para la formulación del Plan Maestro de Gestión del Bosque de Producción Permanente\" - RDE D0000184-2024-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2024,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2024-07-31",
    "kb": 321.0,
    "archivo": "documentos/opr_04_aprobar_lo_lineamientos_para_la_formulacion_del_plan_ma_resolucion.pdf",
    "original": "04_aprobar_lo_lineamientos_para_la_formulacion_del_plan_ma_resolucion.pdf"
  },
  {
    "id": 7,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprobar lo \"Lineamientos para la formulación del Plan Maestro de Gestión del Bosque de Producción Permanente\" - RDE D0000184-2024-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2024,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2024-07-31",
    "kb": 726.0,
    "archivo": "documentos/opr_04_aprobar_lo_lineamientos_para_la_formulacion_del_plan_ma_documento.pdf",
    "original": "04_aprobar_lo_lineamientos_para_la_formulacion_del_plan_ma_documento.pdf"
  },
  {
    "id": 8,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Apruébese la creación de la Nómina de Especialistas del Servicio Nacional Forestal y de Fauna Silvestre - SERFOR; y aprueba los \"Lineamientos para la inscripción, selección y contratación de terceros en la nómina de especialistas del SERFOR\". - RDE D0000072-2024-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2024,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2024-04-15",
    "kb": 382.0,
    "archivo": "documentos/opr_05_apruebese_la_creacion_de_la_nomina_de_especialistas_del_resolucion.pdf",
    "original": "05_apruebese_la_creacion_de_la_nomina_de_especialistas_del_resolucion.pdf"
  },
  {
    "id": 9,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Apruébese la creación de la Nómina de Especialistas del Servicio Nacional Forestal y de Fauna Silvestre - SERFOR; y aprueba los \"Lineamientos para la inscripción, selección y contratación de terceros en la nómina de especialistas del SERFOR\". - RDE D0000072-2024-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2024,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2024-04-15",
    "kb": 542.0,
    "archivo": "documentos/opr_05_apruebese_la_creacion_de_la_nomina_de_especialistas_del_documento.pdf",
    "original": "05_apruebese_la_creacion_de_la_nomina_de_especialistas_del_documento.pdf"
  },
  {
    "id": 10,
    "tipo": "Lineamientos",
    "titulo": "Modificar el numeral 6.5 de los “Lineamientos para el otorgamiento de la autorización del proyecto y autorización de funcionamiento del centro de cría en cautividad. Modificar el numeral 5.3.1 de los “Lineamientos para la elaboración de planes de manejo de fauna silvestre aplicables para zoológicos - RDE D0000020-2024-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2024,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2024-01-23",
    "kb": 357.0,
    "archivo": "documentos/opr_06_modificar_el_numeral_6_5_de_los_lineamientos_para_el_ot_resolucion.pdf",
    "original": "06_modificar_el_numeral_6_5_de_los_lineamientos_para_el_ot_resolucion.pdf"
  },
  {
    "id": 11,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprobar los Lineamientos para la elaboración del Estudio Técnico de Microzonificación. - RDE N° D000270-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-12-15",
    "kb": 300.0,
    "archivo": "documentos/opr_07_aprobar_los_lineamientos_para_la_elaboracion_del_estudi_resolucion.pdf",
    "original": "07_aprobar_los_lineamientos_para_la_elaboracion_del_estudi_resolucion.pdf"
  },
  {
    "id": 12,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprobar los Lineamientos para la elaboración del Estudio Técnico de Microzonificación. - RDE N° D000270-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-12-15",
    "kb": 1324.0,
    "archivo": "documentos/opr_07_aprobar_los_lineamientos_para_la_elaboracion_del_estudi_documento.pdf",
    "original": "07_aprobar_los_lineamientos_para_la_elaboracion_del_estudi_documento.pdf"
  },
  {
    "id": 13,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprobar los “Lineamientos para el otorgamiento de incentivos y/o beneficios por certificación forestal voluntaria y otras buenas prácticas para la competitividad forestal y de fauna silvestre”. - RDE N° D000244-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-11-03",
    "kb": 635.0,
    "archivo": "documentos/opr_09_aprobar_los_lineamientos_para_el_otorgamiento_de_incent_resolucion.pdf",
    "original": "09_aprobar_los_lineamientos_para_el_otorgamiento_de_incent_resolucion.pdf"
  },
  {
    "id": 14,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprobar los “Lineamientos para el otorgamiento de incentivos y/o beneficios por certificación forestal voluntaria y otras buenas prácticas para la competitividad forestal y de fauna silvestre”. - RDE N° D000244-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-11-03",
    "kb": 1202.0,
    "archivo": "documentos/opr_09_aprobar_los_lineamientos_para_el_otorgamiento_de_incent_documento.pdf",
    "original": "09_aprobar_los_lineamientos_para_el_otorgamiento_de_incent_documento.pdf"
  },
  {
    "id": 15,
    "tipo": "Lineamientos",
    "titulo": "[Anexo] Aprobar los “Lineamientos para el otorgamiento de incentivos y/o beneficios por certificación forestal voluntaria y otras buenas prácticas para la competitividad forestal y de fauna silvestre”. - RDE N° D000244-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-11-03",
    "kb": 205.0,
    "archivo": "documentos/opr_09_aprobar_los_lineamientos_para_el_otorgamiento_de_incent_anexo.pdf",
    "original": "09_aprobar_los_lineamientos_para_el_otorgamiento_de_incent_anexo.pdf"
  },
  {
    "id": 16,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprobar los “Lineamientos para el otorgamiento de la autorización de la tenencia de aves de presa procedentes de zoocriaderos para la práctica de cetrería”. - RDE N° D000209-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-09-12",
    "kb": 304.0,
    "archivo": "documentos/opr_10_aprobar_los_lineamientos_para_el_otorgamiento_de_la_aut_resolucion.pdf",
    "original": "10_aprobar_los_lineamientos_para_el_otorgamiento_de_la_aut_resolucion.pdf"
  },
  {
    "id": 17,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprobar los “Lineamientos para el otorgamiento de la autorización de la tenencia de aves de presa procedentes de zoocriaderos para la práctica de cetrería”. - RDE N° D000209-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-09-12",
    "kb": 346.0,
    "archivo": "documentos/opr_10_aprobar_los_lineamientos_para_el_otorgamiento_de_la_aut_documento.pdf",
    "original": "10_aprobar_los_lineamientos_para_el_otorgamiento_de_la_aut_documento.pdf"
  },
  {
    "id": 18,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprobar los “Lineamientos para la elaboración de los libros de registros genealógicos de especies amenazadas de fauna silvestre”. - RDE N° D000167-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-07-24",
    "kb": 296.0,
    "archivo": "documentos/opr_11_aprobar_los_lineamientos_para_la_elaboracion_de_los_lib_resolucion.pdf",
    "original": "11_aprobar_los_lineamientos_para_la_elaboracion_de_los_lib_resolucion.pdf"
  },
  {
    "id": 19,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprobar los “Lineamientos para la elaboración de los libros de registros genealógicos de especies amenazadas de fauna silvestre”. - RDE N° D000167-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-07-24",
    "kb": 407.0,
    "archivo": "documentos/opr_11_aprobar_los_lineamientos_para_la_elaboracion_de_los_lib_documento.pdf",
    "original": "11_aprobar_los_lineamientos_para_la_elaboracion_de_los_lib_documento.pdf"
  },
  {
    "id": 20,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprobar los “Lineamientos para la elaboración de la declaración de manejo de fauna silvestre para centros de conservación”. - RDE N° D000125-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-05-25",
    "kb": 304.0,
    "archivo": "documentos/opr_12_aprobar_los_lineamientos_para_la_elaboracion_de_la_decl_resolucion.pdf",
    "original": "12_aprobar_los_lineamientos_para_la_elaboracion_de_la_decl_resolucion.pdf"
  },
  {
    "id": 21,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprobar los “Lineamientos para la elaboración de la declaración de manejo de fauna silvestre para centros de conservación”. - RDE N° D000125-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-05-25",
    "kb": 924.0,
    "archivo": "documentos/opr_12_aprobar_los_lineamientos_para_la_elaboracion_de_la_decl_documento.pdf",
    "original": "12_aprobar_los_lineamientos_para_la_elaboracion_de_la_decl_documento.pdf"
  },
  {
    "id": 22,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprobar los “Lineamientos para la elaboración de declaraciones de manejo de fauna silvestre para centros de rescate”. - RDE N° D000081-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-03-23",
    "kb": 335.0,
    "archivo": "documentos/opr_13_aprobar_los_lineamientos_para_la_elaboracion_de_declara_resolucion.pdf",
    "original": "13_aprobar_los_lineamientos_para_la_elaboracion_de_declara_resolucion.pdf"
  },
  {
    "id": 23,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprobar los “Lineamientos para la elaboración de declaraciones de manejo de fauna silvestre para centros de rescate”. - RDE N° D000081-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-03-23",
    "kb": 1065.0,
    "archivo": "documentos/opr_13_aprobar_los_lineamientos_para_la_elaboracion_de_declara_documento.pdf",
    "original": "13_aprobar_los_lineamientos_para_la_elaboracion_de_declara_documento.pdf"
  },
  {
    "id": 24,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprobar los “Lineamientos para el Registro, Sistematización y Remisión de la Información Forestal y de Fauna Silvestre”. - RDE N° D000082-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-03-24",
    "kb": 332.0,
    "archivo": "documentos/opr_14_aprobar_los_lineamientos_para_el_registro_sistematizaci_resolucion.pdf",
    "original": "14_aprobar_los_lineamientos_para_el_registro_sistematizaci_resolucion.pdf"
  },
  {
    "id": 25,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprobar los “Lineamientos para el Registro, Sistematización y Remisión de la Información Forestal y de Fauna Silvestre”. - RDE N° D000082-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-03-24",
    "kb": 305.0,
    "archivo": "documentos/opr_14_aprobar_los_lineamientos_para_el_registro_sistematizaci_documento.pdf",
    "original": "14_aprobar_los_lineamientos_para_el_registro_sistematizaci_documento.pdf"
  },
  {
    "id": 26,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprobar los “Lineamientos para la transferencia de productos, subproductos, o especímenes forestales decomisados o declarados en abandono”. - RDE N° D000075-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-03-18",
    "kb": 298.0,
    "archivo": "documentos/opr_15_aprobar_los_lineamientos_para_la_transferencia_de_produ_resolucion.pdf",
    "original": "15_aprobar_los_lineamientos_para_la_transferencia_de_produ_resolucion.pdf"
  },
  {
    "id": 27,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprobar los “Lineamientos para la transferencia de productos, subproductos, o especímenes forestales decomisados o declarados en abandono”. - RDE N° D000075-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-03-18",
    "kb": 622.0,
    "archivo": "documentos/opr_15_aprobar_los_lineamientos_para_la_transferencia_de_produ_documento.pdf",
    "original": "15_aprobar_los_lineamientos_para_la_transferencia_de_produ_documento.pdf"
  },
  {
    "id": 28,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprobar los “Lineamientos para la elaboración de la declaración de manejo para el aprovechamiento forestal en bosques secundarios”. - RDE N° D000064-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-03-09",
    "kb": 272.0,
    "archivo": "documentos/opr_16_aprobar_los_lineamientos_para_la_elaboracion_de_la_decl_resolucion.pdf",
    "original": "16_aprobar_los_lineamientos_para_la_elaboracion_de_la_decl_resolucion.pdf"
  },
  {
    "id": 29,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprobar los “Lineamientos para la elaboración de la declaración de manejo para el aprovechamiento forestal en bosques secundarios”. - RDE N° D000064-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-03-09",
    "kb": 589.0,
    "archivo": "documentos/opr_16_aprobar_los_lineamientos_para_la_elaboracion_de_la_decl_documento.pdf",
    "original": "16_aprobar_los_lineamientos_para_la_elaboracion_de_la_decl_documento.pdf"
  },
  {
    "id": 30,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprobar los “Lineamientos para la elaboración de la declaración de manejo para el aprovechamiento forestal maderable en bosques secos”. - RDE N° D000061-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-03-08",
    "kb": 273.0,
    "archivo": "documentos/opr_17_aprobar_los_lineamientos_para_la_elaboracion_de_la_decl_resolucion.pdf",
    "original": "17_aprobar_los_lineamientos_para_la_elaboracion_de_la_decl_resolucion.pdf"
  },
  {
    "id": 31,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprobar los “Lineamientos para la elaboración de la declaración de manejo para el aprovechamiento forestal maderable en bosques secos”. - RDE N° D000061-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-03-08",
    "kb": 1041.0,
    "archivo": "documentos/opr_17_aprobar_los_lineamientos_para_la_elaboracion_de_la_decl_documento.pdf",
    "original": "17_aprobar_los_lineamientos_para_la_elaboracion_de_la_decl_documento.pdf"
  },
  {
    "id": 32,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprobar los “Lineamientos para el otorgamiento de autorizaciones de cambio de uso actual de la tierra para fines agropecuarios en tierras de dominio público”. - RDE N° D000038-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-02-10",
    "kb": 332.0,
    "archivo": "documentos/opr_18_aprobar_los_lineamientos_para_el_otorgamiento_de_autori_resolucion.pdf",
    "original": "18_aprobar_los_lineamientos_para_el_otorgamiento_de_autori_resolucion.pdf"
  },
  {
    "id": 33,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprobar los “Lineamientos para el otorgamiento de autorizaciones de cambio de uso actual de la tierra para fines agropecuarios en tierras de dominio público”. - RDE N° D000038-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-02-10",
    "kb": 768.0,
    "archivo": "documentos/opr_18_aprobar_los_lineamientos_para_el_otorgamiento_de_autori_documento.pdf",
    "original": "18_aprobar_los_lineamientos_para_el_otorgamiento_de_autori_documento.pdf"
  },
  {
    "id": 34,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprobar los “Lineamientos para la realización de auditorías y verificaciones a productores y exportadores de productos forestales maderables”. - RDE N° D000012-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-01-10",
    "kb": 305.0,
    "archivo": "documentos/opr_19_aprobar_los_lineamientos_para_la_realizacion_de_auditor_resolucion.pdf",
    "original": "19_aprobar_los_lineamientos_para_la_realizacion_de_auditor_resolucion.pdf"
  },
  {
    "id": 35,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprobar los “Lineamientos para la realización de auditorías y verificaciones a productores y exportadores de productos forestales maderables”. - RDE N° D000012-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-01-10",
    "kb": 358.0,
    "archivo": "documentos/opr_19_aprobar_los_lineamientos_para_la_realizacion_de_auditor_documento.pdf",
    "original": "19_aprobar_los_lineamientos_para_la_realizacion_de_auditor_documento.pdf"
  },
  {
    "id": 36,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprobar los “Lineamientos para la compensación de multas por infracción a la legislación forestal y de fauna silvestre”. - RDE N° D000268-2022-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2022,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2022-11-14",
    "kb": 264.0,
    "archivo": "documentos/opr_20_aprobar_los_lineamientos_para_la_compensacion_de_multas_resolucion.pdf",
    "original": "20_aprobar_los_lineamientos_para_la_compensacion_de_multas_resolucion.pdf"
  },
  {
    "id": 37,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprobar los “Lineamientos para la compensación de multas por infracción a la legislación forestal y de fauna silvestre”. - RDE N° D000268-2022-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2022,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2022-11-14",
    "kb": 296.0,
    "archivo": "documentos/opr_20_aprobar_los_lineamientos_para_la_compensacion_de_multas_documento.pdf",
    "original": "20_aprobar_los_lineamientos_para_la_compensacion_de_multas_documento.pdf"
  },
  {
    "id": 38,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprobar los “Lineamientos para la ampliación de la vigencia de los contratos de concesión forestal y de los contratos de concesión de fauna silvestre”. - RDE N° D000175-2022-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2022,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2022-08-05",
    "kb": 288.0,
    "archivo": "documentos/opr_21_aprobar_los_lineamientos_para_la_ampliacion_de_la_vigen_resolucion.pdf",
    "original": "21_aprobar_los_lineamientos_para_la_ampliacion_de_la_vigen_resolucion.pdf"
  },
  {
    "id": 39,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprobar los “Lineamientos para la ampliación de la vigencia de los contratos de concesión forestal y de los contratos de concesión de fauna silvestre”. - RDE N° D000175-2022-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2022,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2022-08-05",
    "kb": 816.0,
    "archivo": "documentos/opr_21_aprobar_los_lineamientos_para_la_ampliacion_de_la_vigen_documento.pdf",
    "original": "21_aprobar_los_lineamientos_para_la_ampliacion_de_la_vigen_documento.pdf"
  },
  {
    "id": 40,
    "tipo": "Lineamientos",
    "titulo": "Aprobar los Lineamientos para elaboración de planes de manejo de fauna silvestre aplicables en zoológicos. - RDE N° D000017-2022-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2022,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2022-01-19",
    "kb": 306.0,
    "archivo": "documentos/opr_22_aprobar_los_lineamientos_para_elaboracion_de_planes_de_resolucion.pdf",
    "original": "22_aprobar_los_lineamientos_para_elaboracion_de_planes_de_resolucion.pdf"
  },
  {
    "id": 41,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprobar los “Lineamientos para el otorgamiento de la autorización a personas naturales para la tenencia de especímenes de fauna silvestre nativa y exótica”. - RDE N° D000107-2021-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2021,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2021-06-25",
    "kb": 327.0,
    "archivo": "documentos/opr_23_aprobar_los_lineamientos_para_el_otorgamiento_de_la_aut_resolucion.pdf",
    "original": "23_aprobar_los_lineamientos_para_el_otorgamiento_de_la_aut_resolucion.pdf"
  },
  {
    "id": 42,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprobar los “Lineamientos para el otorgamiento de la autorización a personas naturales para la tenencia de especímenes de fauna silvestre nativa y exótica”. - RDE N° D000107-2021-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2021,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2021-06-25",
    "kb": 513.0,
    "archivo": "documentos/opr_23_aprobar_los_lineamientos_para_el_otorgamiento_de_la_aut_documento.pdf",
    "original": "23_aprobar_los_lineamientos_para_el_otorgamiento_de_la_aut_documento.pdf"
  },
  {
    "id": 43,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprobar los Lineamientos para la elaboración e implementación de los planes de cierre de las concesiones forestales y de fauna silvestre - RDE N° D000069-2021-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2021,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2021-04-21",
    "kb": 349.0,
    "archivo": "documentos/opr_24_aprobar_los_lineamientos_para_la_elaboracion_e_implemen_resolucion.pdf",
    "original": "24_aprobar_los_lineamientos_para_la_elaboracion_e_implemen_resolucion.pdf"
  },
  {
    "id": 44,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprobar los Lineamientos para la elaboración e implementación de los planes de cierre de las concesiones forestales y de fauna silvestre - RDE N° D000069-2021-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2021,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2021-04-21",
    "kb": 295.0,
    "archivo": "documentos/opr_24_aprobar_los_lineamientos_para_la_elaboracion_e_implemen_documento.pdf",
    "original": "24_aprobar_los_lineamientos_para_la_elaboracion_e_implemen_documento.pdf"
  },
  {
    "id": 45,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprobar los Lineamientos para la evaluación de planes operativos, declaraciones de manejo y planes de manejo forestal intermedio - RDE N° D000036-2021-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2021,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2021-03-05",
    "kb": 289.0,
    "archivo": "documentos/opr_25_aprobar_los_lineamientos_para_la_evaluacion_de_planes_o_resolucion.pdf",
    "original": "25_aprobar_los_lineamientos_para_la_evaluacion_de_planes_o_resolucion.pdf"
  },
  {
    "id": 46,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprobar los Lineamientos para la evaluación de planes operativos, declaraciones de manejo y planes de manejo forestal intermedio - RDE N° D000036-2021-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2021,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2021-03-05",
    "kb": 388.0,
    "archivo": "documentos/opr_25_aprobar_los_lineamientos_para_la_evaluacion_de_planes_o_documento.pdf",
    "original": "25_aprobar_los_lineamientos_para_la_evaluacion_de_planes_o_documento.pdf"
  },
  {
    "id": 47,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprobar los Lineamientos para la evaluación del Plan General de Manejo Forestal de concesiones forestales con fines maderables - RDE N° D000034-2021-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2021,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2021-03-04",
    "kb": 285.0,
    "archivo": "documentos/opr_26_aprobar_los_lineamientos_para_la_evaluacion_del_plan_ge_resolucion.pdf",
    "original": "26_aprobar_los_lineamientos_para_la_evaluacion_del_plan_ge_resolucion.pdf"
  },
  {
    "id": 48,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprobar los Lineamientos para la evaluación del Plan General de Manejo Forestal de concesiones forestales con fines maderables - RDE N° D000034-2021-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2021,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2021-03-04",
    "kb": 364.0,
    "archivo": "documentos/opr_26_aprobar_los_lineamientos_para_la_evaluacion_del_plan_ge_documento.pdf",
    "original": "26_aprobar_los_lineamientos_para_la_evaluacion_del_plan_ge_documento.pdf"
  },
  {
    "id": 49,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprobar la versión actualizada del documento técnico denominado “Trazabilidad de los Recursos Forestales Maderables” - RDE N° D000135-2020-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2020,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2020-12-28",
    "kb": 308.0,
    "archivo": "documentos/opr_27_aprobar_la_version_actualizada_del_documento_tecnico_de_resolucion.pdf",
    "original": "27_aprobar_la_version_actualizada_del_documento_tecnico_de_resolucion.pdf"
  },
  {
    "id": 50,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprobar la versión actualizada del documento técnico denominado “Trazabilidad de los Recursos Forestales Maderables” - RDE N° D000135-2020-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2020,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2020-12-28",
    "kb": 809.0,
    "archivo": "documentos/opr_27_aprobar_la_version_actualizada_del_documento_tecnico_de_documento.pdf",
    "original": "27_aprobar_la_version_actualizada_del_documento_tecnico_de_documento.pdf"
  },
  {
    "id": 51,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprobar los lineamientos para el reconocimiento o acreditación de Custodios del Patrimonio Forestal y de Fauna Silvestre de la Nación - RDE N° D0081-2020-MINAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2020,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2020-09-24",
    "kb": 286.0,
    "archivo": "documentos/opr_28_aprobar_los_lineamientos_para_el_reconocimiento_o_acred_resolucion.pdf",
    "original": "28_aprobar_los_lineamientos_para_el_reconocimiento_o_acred_resolucion.pdf"
  },
  {
    "id": 52,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprobar los lineamientos para el reconocimiento o acreditación de Custodios del Patrimonio Forestal y de Fauna Silvestre de la Nación - RDE N° D0081-2020-MINAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2020,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2020-09-24",
    "kb": 319.0,
    "archivo": "documentos/opr_28_aprobar_los_lineamientos_para_el_reconocimiento_o_acred_documento.pdf",
    "original": "28_aprobar_los_lineamientos_para_el_reconocimiento_o_acred_documento.pdf"
  },
  {
    "id": 53,
    "tipo": "Lineamientos",
    "titulo": "Aprueba Lineamientos prevención control y acciones para mitigar el riesgo de propagación del COVID-19 - RDE N° 0045-2020-MINAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2020,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2020-04-27",
    "kb": 1481.0,
    "archivo": "documentos/opr_29_aprueba_lineamientos_prevencion_control_y_acciones_para_resolucion.pdf",
    "original": "29_aprueba_lineamientos_prevencion_control_y_acciones_para_resolucion.pdf"
  },
  {
    "id": 54,
    "tipo": "Lineamientos",
    "titulo": "Aprobar los Lineamientos para el seguimiento y evaluación de políticas, estrategias, planes programas y proyectos en materia forestal y de fauna silvestre del SERFOR - RDE N° 0043-2020-MINAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2020,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2020-03-13",
    "kb": 10626.0,
    "archivo": "documentos/opr_30_aprobar_los_lineamientos_para_el_seguimiento_y_evaluaci_resolucion.pdf",
    "original": "30_aprobar_los_lineamientos_para_el_seguimiento_y_evaluaci_resolucion.pdf"
  },
  {
    "id": 55,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprueban la Estrategia para la Promoción de Plantaciones Forestales Comerciales 2021-2050 - RDE Nº 0190-2021-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2021,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2021-10-11",
    "kb": 322.0,
    "archivo": "documentos/opr_33_aprueban_la_estrategia_para_la_promocion_de_plantacione_resolucion.pdf",
    "original": "33_aprueban_la_estrategia_para_la_promocion_de_plantacione_resolucion.pdf"
  },
  {
    "id": 56,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Aprueban la Estrategia para la Promoción de Plantaciones Forestales Comerciales 2021-2050 - RDE Nº 0190-2021-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2021,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2021-10-11",
    "kb": 2033.0,
    "archivo": "documentos/opr_33_aprueban_la_estrategia_para_la_promocion_de_plantacione_documento.pdf",
    "original": "33_aprueban_la_estrategia_para_la_promocion_de_plantacione_documento.pdf"
  },
  {
    "id": 57,
    "tipo": "Lineamientos",
    "titulo": "Aprobar los Lineamientos para establecer hábitats críticos y sus medidas de conservación - RDE N° 0261-2019-MINAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2019,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2019-12-23",
    "kb": 6393.0,
    "archivo": "documentos/opr_35_aprobar_los_lineamientos_para_establecer_habitats_criti_resolucion.pdf",
    "original": "35_aprobar_los_lineamientos_para_establecer_habitats_criti_resolucion.pdf"
  },
  {
    "id": 58,
    "tipo": "Lineamientos",
    "titulo": "Aprobar los Lineamientos para la identificación de Ecosistemas Frágiles y su incorporación en la Lista Sectorial de Ecosistemas Frágiles - RDE N° 0287-2018-MINAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2018,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2018-12-19",
    "kb": 12407.0,
    "archivo": "documentos/opr_37_aprobar_los_lineamientos_para_la_identificacion_de_ecos_resolucion.pdf",
    "original": "37_aprobar_los_lineamientos_para_la_identificacion_de_ecos_resolucion.pdf"
  },
  {
    "id": 59,
    "tipo": "Lineamientos",
    "titulo": "Aprobar los lineamientos para la elaboración de declaración de manejo de concesiones para ecoturismo - RDE N° 0263-2018-MINAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2018,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2018-11-21",
    "kb": 5646.0,
    "archivo": "documentos/opr_38_aprobar_los_lineamientos_para_la_elaboracion_de_declara_resolucion.pdf",
    "original": "38_aprobar_los_lineamientos_para_la_elaboracion_de_declara_resolucion.pdf"
  },
  {
    "id": 60,
    "tipo": "Lineamientos",
    "titulo": "Aprobar los lineamientos para la el otorgamiento de autorizaciones forestales para el aprovechamiento de productos forestales diferentes a la madera en asociaciones vegetales - RDE N° 0258-2018-MINAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2018,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2018-11-13",
    "kb": 6512.0,
    "archivo": "documentos/opr_39_aprobar_los_lineamientos_para_la_el_otorgamiento_de_aut_resolucion.pdf",
    "original": "39_aprobar_los_lineamientos_para_la_el_otorgamiento_de_aut_resolucion.pdf"
  },
  {
    "id": 61,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Aprobar los lineamientos para la restauración de ecosistemas forestales y otros ecosistemas de vegetación silvestre - RDE N° 0083-2018-MINAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2018,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2018-04-23",
    "kb": 7094.0,
    "archivo": "documentos/opr_40_aprobar_los_lineamientos_para_la_restauracion_de_ecosis_resolucion.pdf",
    "original": "40_aprobar_los_lineamientos_para_la_restauracion_de_ecosis_resolucion.pdf"
  },
  {
    "id": 62,
    "tipo": "Lineamientos",
    "titulo": "[Anexo] Aprobar los lineamientos para la restauración de ecosistemas forestales y otros ecosistemas de vegetación silvestre - RDE N° 0083-2018-MINAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2018,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2018-04-23",
    "kb": 10539.0,
    "archivo": "documentos/opr_40_aprobar_los_lineamientos_para_la_restauracion_de_ecosis_anexo.pdf",
    "original": "40_aprobar_los_lineamientos_para_la_restauracion_de_ecosis_anexo.pdf"
  },
  {
    "id": 63,
    "tipo": "Lineamientos",
    "titulo": "Aprobar los lineamientos para la elaboración del calendario regional de caza deportiva - RDE N° 0073-2018-MINAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2018,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2018-04-10",
    "kb": 5049.0,
    "archivo": "documentos/opr_41_aprobar_los_lineamientos_para_la_elaboracion_del_calend_resolucion.pdf",
    "original": "41_aprobar_los_lineamientos_para_la_elaboracion_del_calend_resolucion.pdf"
  },
  {
    "id": 64,
    "tipo": "Lineamientos",
    "titulo": "Aprobar los lineamientos para la elaboración de declaración de manejo para permisos de aprovechamiento forestal en predios privados - RDE N° 0052-2018-MINAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2018,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2018-03-20",
    "kb": 4799.0,
    "archivo": "documentos/opr_42_aprobar_los_lineamientos_para_la_elaboracion_de_declara_resolucion.pdf",
    "original": "42_aprobar_los_lineamientos_para_la_elaboracion_de_declara_resolucion.pdf"
  },
  {
    "id": 65,
    "tipo": "Lineamientos",
    "titulo": "Aprobar los \"Lineamientos para la aplicación de los criterios de gradualidad para la imposición de la sanción pecuniaria\" - RDE Nº 0004-2018-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2018,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2018-01-09",
    "kb": 4644.0,
    "archivo": "documentos/opr_43_aprobar_los_lineamientos_para_la_aplicacion_de_los_crit_resolucion.pdf",
    "original": "43_aprobar_los_lineamientos_para_la_aplicacion_de_los_crit_resolucion.pdf"
  },
  {
    "id": 66,
    "tipo": "Lineamientos",
    "titulo": "Aprobar los Lineamientos para el otorgamiento de la autorización de proyecto y funcionamiento del centro de cría en cautividad. - RDE Nº 0147-2017-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2017,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2017-06-09",
    "kb": 1238.0,
    "archivo": "documentos/opr_47_aprobar_los_lineamientos_para_el_otorgamiento_de_la_aut_resolucion.pdf",
    "original": "47_aprobar_los_lineamientos_para_el_otorgamiento_de_la_aut_resolucion.pdf"
  },
  {
    "id": 67,
    "tipo": "Lineamientos",
    "titulo": "Aprobar los Lineamientos para el otorgamiento de permisos para manejo de fauna silvestre en predios privados. - RDE Nº 0146-2017-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2017,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2017-06-09",
    "kb": 936.0,
    "archivo": "documentos/opr_48_aprobar_los_lineamientos_para_el_otorgamiento_de_permis_resolucion.pdf",
    "original": "48_aprobar_los_lineamientos_para_el_otorgamiento_de_permis_resolucion.pdf"
  },
  {
    "id": 68,
    "tipo": "Lineamientos",
    "titulo": "Aprobar los Lineamientos para el otorgamiento de concesiones para plantaciones forestales por concesión directa. - RDE Nº 0133-2017-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2017,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2017-05-24",
    "kb": 2850.0,
    "archivo": "documentos/opr_49_aprobar_los_lineamientos_para_el_otorgamiento_de_conces_resolucion.pdf",
    "original": "49_aprobar_los_lineamientos_para_el_otorgamiento_de_conces_resolucion.pdf"
  },
  {
    "id": 69,
    "tipo": "Lineamientos",
    "titulo": "Aprobar los lineamientos para el otorgamiento de contratos de cesión en uso para sistemas agroforestales - RDE Nº 0081-2017-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2017,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2017-03-31",
    "kb": 5360.0,
    "archivo": "documentos/opr_52_aprobar_los_lineamientos_para_el_otorgamiento_de_contra_resolucion.pdf",
    "original": "52_aprobar_los_lineamientos_para_el_otorgamiento_de_contra_resolucion.pdf"
  },
  {
    "id": 70,
    "tipo": "Lineamientos",
    "titulo": "Aprobar los Lineamientos para el otorgamiento de concesiones forestales con fines maderables por procedimiento abreviado - RDE Nº 0078-2017-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2017,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2017-03-30",
    "kb": 3271.0,
    "archivo": "documentos/opr_53_aprobar_los_lineamientos_para_el_otorgamiento_de_conces_resolucion.pdf",
    "original": "53_aprobar_los_lineamientos_para_el_otorgamiento_de_conces_resolucion.pdf"
  },
  {
    "id": 71,
    "tipo": "Lineamientos",
    "titulo": "Aprobar los Lineamientos para el otorgamiento de la autorización para la captura comercial de fauna silvestre - RDE Nº 0282-2016-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2016,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2016-12-28",
    "kb": 167.0,
    "archivo": "documentos/opr_54_aprobar_los_lineamientos_para_el_otorgamiento_de_la_aut_resolucion.pdf",
    "original": "54_aprobar_los_lineamientos_para_el_otorgamiento_de_la_aut_resolucion.pdf"
  },
  {
    "id": 72,
    "tipo": "Lineamientos",
    "titulo": "Aprobar los Lineamientos para elaboración de la declaración de manejo de concesiones de conservación - RDE Nº 0281-2016-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2016,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2016-12-28",
    "kb": 149.0,
    "archivo": "documentos/opr_55_aprobar_los_lineamientos_para_elaboracion_de_la_declara_resolucion.pdf",
    "original": "55_aprobar_los_lineamientos_para_elaboracion_de_la_declara_resolucion.pdf"
  },
  {
    "id": 73,
    "tipo": "Lineamientos",
    "titulo": "Aprobar los “Lineamientos para autorizar la realización de estudios del patrimonio en el marco del instrumento de gestión ambiental”. - RDE N° D0026-2020-MINAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2020,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2020-07-26",
    "kb": 345.0,
    "archivo": "documentos/opr_90_aprobar_los_lineamientos_para_autorizar_la_realizacion_resolucion.pdf",
    "original": "90_aprobar_los_lineamientos_para_autorizar_la_realizacion_resolucion.pdf"
  },
  {
    "id": 74,
    "tipo": "Lineamientos",
    "titulo": "[Resolucion] Lineamientos para el otorgamiento de la autorización de desbosque - RDE N° D000044-2025-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2025,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2025-02-26",
    "kb": 329.0,
    "archivo": "documentos/opr_95_lineamientos_para_el_otorgamiento_de_la_autorizacion_de_resolucion.pdf",
    "original": "95_lineamientos_para_el_otorgamiento_de_la_autorizacion_de_resolucion.pdf"
  },
  {
    "id": 75,
    "tipo": "Lineamientos",
    "titulo": "[Lineamiento] Lineamientos para el otorgamiento de la autorización de desbosque - RDE N° D000044-2025-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2025,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2025-02-26",
    "kb": 1671.0,
    "archivo": "documentos/opr_95_lineamientos_para_el_otorgamiento_de_la_autorizacion_de_documento.pdf",
    "original": "95_lineamientos_para_el_otorgamiento_de_la_autorizacion_de_documento.pdf"
  },
  {
    "id": 76,
    "tipo": "Directiva",
    "titulo": "[Resolucion] Aprobar la Directiva General N° D000001-2025-MIDAGRI-SERFOR-GG: Directiva que regula el reconocimiento de los servidores civiles del servicio nacional forestal y de fauna silvestre - SERFOR - RGG N° D00002-2025-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2025,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2025-01-06",
    "kb": 370.0,
    "archivo": "documentos/opr_01_aprobar_la_directiva_general_n_d000001_2025_midagri_ser_resolucion.pdf",
    "original": "01_aprobar_la_directiva_general_n_d000001_2025_midagri_ser_resolucion.pdf"
  },
  {
    "id": 77,
    "tipo": "Directiva",
    "titulo": "[Directiva] Aprobar la Directiva General N° D000001-2025-MIDAGRI-SERFOR-GG: Directiva que regula el reconocimiento de los servidores civiles del servicio nacional forestal y de fauna silvestre - SERFOR - RGG N° D00002-2025-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2025,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2025-01-06",
    "kb": 587.0,
    "archivo": "documentos/opr_01_aprobar_la_directiva_general_n_d000001_2025_midagri_ser_documento.pdf",
    "original": "01_aprobar_la_directiva_general_n_d000001_2025_midagri_ser_documento.pdf"
  },
  {
    "id": 78,
    "tipo": "Directiva",
    "titulo": "[Resolucion] Directiva de prevención, atención de denuncia, investigación y sanción de actos de hostigamiento sexual en el servicio nacional forestal y de fauna silvestre - SERFOR - RGG N° D000029-2024-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2024,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2024-12-27",
    "kb": 433.0,
    "archivo": "documentos/opr_03_directiva_de_prevencion_atencion_de_denuncia_investigac_resolucion.pdf",
    "original": "03_directiva_de_prevencion_atencion_de_denuncia_investigac_resolucion.pdf"
  },
  {
    "id": 79,
    "tipo": "Directiva",
    "titulo": "[Directiva] Directiva de prevención, atención de denuncia, investigación y sanción de actos de hostigamiento sexual en el servicio nacional forestal y de fauna silvestre - SERFOR - RGG N° D000029-2024-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2024,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2024-12-27",
    "kb": 833.0,
    "archivo": "documentos/opr_03_directiva_de_prevencion_atencion_de_denuncia_investigac_documento.pdf",
    "original": "03_directiva_de_prevencion_atencion_de_denuncia_investigac_documento.pdf"
  },
  {
    "id": 80,
    "tipo": "Directiva",
    "titulo": "Directiva General N° D000003-2024-MIDAGRI-SERFOR-GG, “Directiva denominada “Implementación de la Gestión por Procesos en el SERFOR - RGG N° D000014-2024-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2024,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2024-07-19",
    "kb": 956.0,
    "archivo": "documentos/opr_04_directiva_general_n_d000003_2024_midagri_serfor_gg_dire_resolucion.pdf",
    "original": "04_directiva_general_n_d000003_2024_midagri_serfor_gg_dire_resolucion.pdf"
  },
  {
    "id": 81,
    "tipo": "Directiva",
    "titulo": "[Resolucion] Aprobar la Directiva General N° D000004-2024-MIDAGRI-SERFOR-GG denominada “Directiva para la Gestión de la Ecoeficiencia en el Servicio Nacional Forestal y de Fauna Silvestre – SERFOR” - RGG Nº 0015-2024-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2024,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2024-08-09",
    "kb": 414.0,
    "archivo": "documentos/opr_05_aprobar_la_directiva_general_n_d000004_2024_midagri_ser_resolucion.pdf",
    "original": "05_aprobar_la_directiva_general_n_d000004_2024_midagri_ser_resolucion.pdf"
  },
  {
    "id": 82,
    "tipo": "Directiva",
    "titulo": "[Directiva] Aprobar la Directiva General N° D000004-2024-MIDAGRI-SERFOR-GG denominada “Directiva para la Gestión de la Ecoeficiencia en el Servicio Nacional Forestal y de Fauna Silvestre – SERFOR” - RGG Nº 0015-2024-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2024,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2024-08-09",
    "kb": 900.0,
    "archivo": "documentos/opr_05_aprobar_la_directiva_general_n_d000004_2024_midagri_ser_documento.pdf",
    "original": "05_aprobar_la_directiva_general_n_d000004_2024_midagri_ser_documento.pdf"
  },
  {
    "id": 83,
    "tipo": "Directiva",
    "titulo": "Aprobar la Directiva General N° D000004-2023-MIDAGRI-SERFOR-GG denominada “Normas para la Implementación y Funcionamiento del Lactario Institucional en el SERFOR - RGG N° D00028-2023-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-08-31",
    "kb": 327.0,
    "archivo": "documentos/opr_06_aprobar_la_directiva_general_n_d000004_2023_midagri_ser_resolucion.pdf",
    "original": "06_aprobar_la_directiva_general_n_d000004_2023_midagri_ser_resolucion.pdf"
  },
  {
    "id": 84,
    "tipo": "Directiva",
    "titulo": "[Resolucion] Aprobar la Directiva N°0002-2023-MIDAGRI SERFOR PKFW \"Directiva para la toma de inventario físico de bienes muebles patrimoniales del programa Fomento y Gestión sostenible de la producción forestal en el Perú - RCE N° D000004-2023-MIDAGRI-SERFOR-PKFW",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-03-08",
    "kb": 496.0,
    "archivo": "documentos/opr_08_aprobar_la_directiva_n_0002_2023_midagri_serfor_pkfw_di_resolucion.pdf",
    "original": "08_aprobar_la_directiva_n_0002_2023_midagri_serfor_pkfw_di_resolucion.pdf"
  },
  {
    "id": 85,
    "tipo": "Directiva",
    "titulo": "[Directiva] Aprobar la Directiva N°0002-2023-MIDAGRI SERFOR PKFW \"Directiva para la toma de inventario físico de bienes muebles patrimoniales del programa Fomento y Gestión sostenible de la producción forestal en el Perú - RCE N° D000004-2023-MIDAGRI-SERFOR-PKFW",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-03-08",
    "kb": 653.0,
    "archivo": "documentos/opr_08_aprobar_la_directiva_n_0002_2023_midagri_serfor_pkfw_di_documento.pdf",
    "original": "08_aprobar_la_directiva_n_0002_2023_midagri_serfor_pkfw_di_documento.pdf"
  },
  {
    "id": 86,
    "tipo": "Directiva",
    "titulo": "[Resolucion] Aprobar la Directiva General denominada “Directiva para el Registro, Sistematización y Remisión de la Información Forestal y de Fauna Silvestre”. - RDE N° D000030-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-02-07",
    "kb": 302.0,
    "archivo": "documentos/opr_09_aprobar_la_directiva_general_denominada_directiva_para_resolucion.pdf",
    "original": "09_aprobar_la_directiva_general_denominada_directiva_para_resolucion.pdf"
  },
  {
    "id": 87,
    "tipo": "Directiva",
    "titulo": "[Directiva] Aprobar la Directiva General denominada “Directiva para el Registro, Sistematización y Remisión de la Información Forestal y de Fauna Silvestre”. - RDE N° D000030-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-02-07",
    "kb": 454.0,
    "archivo": "documentos/opr_09_aprobar_la_directiva_general_denominada_directiva_para_documento.pdf",
    "original": "09_aprobar_la_directiva_general_denominada_directiva_para_documento.pdf"
  },
  {
    "id": 88,
    "tipo": "Directiva",
    "titulo": "[Anexo] Aprobar la Directiva General denominada “Directiva para el Registro, Sistematización y Remisión de la Información Forestal y de Fauna Silvestre”. - RDE N° D000030-2023-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-02-07",
    "kb": 275.0,
    "archivo": "documentos/opr_09_aprobar_la_directiva_general_denominada_directiva_para_anexo.pdf",
    "original": "09_aprobar_la_directiva_general_denominada_directiva_para_anexo.pdf"
  },
  {
    "id": 89,
    "tipo": "Directiva",
    "titulo": "[Resolucion] Aprobar la Directiva General Nº D000006-2022-MIDAGRI-SERFOR-GG “Código de Conducta Institucional del Servicio Nacional Forestal y de Fauna Silvestre - SERFOR”. - RGG N° D0039-2022-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2022,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2022-11-18",
    "kb": 385.0,
    "archivo": "documentos/opr_14_aprobar_la_directiva_general_n_d000006_2022_midagri_ser_resolucion.pdf",
    "original": "14_aprobar_la_directiva_general_n_d000006_2022_midagri_ser_resolucion.pdf"
  },
  {
    "id": 90,
    "tipo": "Directiva",
    "titulo": "[Directiva] Aprobar la Directiva General Nº D000006-2022-MIDAGRI-SERFOR-GG “Código de Conducta Institucional del Servicio Nacional Forestal y de Fauna Silvestre - SERFOR”. - RGG N° D0039-2022-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2022,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2022-11-18",
    "kb": 446.0,
    "archivo": "documentos/opr_14_aprobar_la_directiva_general_n_d000006_2022_midagri_ser_documento.pdf",
    "original": "14_aprobar_la_directiva_general_n_d000006_2022_midagri_ser_documento.pdf"
  },
  {
    "id": 91,
    "tipo": "Directiva",
    "titulo": "[Resolucion] Aprobar la actualización de la Directiva General denominada “Directiva de Gestión Documental del - SERFOR”. - RGG N° D0026-2022-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2022,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2022-09-08",
    "kb": 347.0,
    "archivo": "documentos/opr_15_aprobar_la_actualizacion_de_la_directiva_general_denomi_resolucion.pdf",
    "original": "15_aprobar_la_actualizacion_de_la_directiva_general_denomi_resolucion.pdf"
  },
  {
    "id": 92,
    "tipo": "Directiva",
    "titulo": "[Directiva] Aprobar la actualización de la Directiva General denominada “Directiva de Gestión Documental del - SERFOR”. - RGG N° D0026-2022-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2022,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2022-09-08",
    "kb": 2634.0,
    "archivo": "documentos/opr_15_aprobar_la_actualizacion_de_la_directiva_general_denomi_documento.pdf",
    "original": "15_aprobar_la_actualizacion_de_la_directiva_general_denomi_documento.pdf"
  },
  {
    "id": 93,
    "tipo": "Directiva",
    "titulo": "[Resolucion] Aprobar la Directiva General Nº D000004-2022-MIDAGRI-SERFOR-GG “Directiva para la Gestión Editorial del Servicio Nacional Forestal y de Fauna Silvestre – SERFOR”. - RGG N° D0021-2022-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2022,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2022-08-23",
    "kb": 366.0,
    "archivo": "documentos/opr_16_aprobar_la_directiva_general_n_d000004_2022_midagri_ser_resolucion.pdf",
    "original": "16_aprobar_la_directiva_general_n_d000004_2022_midagri_ser_resolucion.pdf"
  },
  {
    "id": 94,
    "tipo": "Directiva",
    "titulo": "[Directiva] Aprobar la Directiva General Nº D000004-2022-MIDAGRI-SERFOR-GG “Directiva para la Gestión Editorial del Servicio Nacional Forestal y de Fauna Silvestre – SERFOR”. - RGG N° D0021-2022-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2022,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2022-08-23",
    "kb": 836.0,
    "archivo": "documentos/opr_16_aprobar_la_directiva_general_n_d000004_2022_midagri_ser_documento.pdf",
    "original": "16_aprobar_la_directiva_general_n_d000004_2022_midagri_ser_documento.pdf"
  },
  {
    "id": 95,
    "tipo": "Directiva",
    "titulo": "[Resolucion] Aprobar la Directiva denominada “Directiva del Servicio de Soporte Tecnológico de la Información del SERFOR”. - RGG N° D0019-2022-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2022,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2022-07-12",
    "kb": 337.0,
    "archivo": "documentos/opr_17_aprobar_la_directiva_denominada_directiva_del_servicio_resolucion.pdf",
    "original": "17_aprobar_la_directiva_denominada_directiva_del_servicio_resolucion.pdf"
  },
  {
    "id": 96,
    "tipo": "Directiva",
    "titulo": "[Directiva] Aprobar la Directiva denominada “Directiva del Servicio de Soporte Tecnológico de la Información del SERFOR”. - RGG N° D0019-2022-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2022,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2022-07-12",
    "kb": 1467.0,
    "archivo": "documentos/opr_17_aprobar_la_directiva_denominada_directiva_del_servicio_documento.pdf",
    "original": "17_aprobar_la_directiva_denominada_directiva_del_servicio_documento.pdf"
  },
  {
    "id": 97,
    "tipo": "Directiva",
    "titulo": "[Resolucion] Directiva General Código de Conducta Institucional del Servicio Nacional Forestal y de Fauna Silvestre – SERFOR - RGG N° D000039-2022-MIDAGRI-SERFOR.GG",
    "entidad": "SERFOR",
    "anio": 2022,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2022-11-18",
    "kb": 385.0,
    "archivo": "documentos/opr_19_directiva_general_codigo_de_conducta_institucional_del_resolucion.pdf",
    "original": "19_directiva_general_codigo_de_conducta_institucional_del_resolucion.pdf"
  },
  {
    "id": 98,
    "tipo": "Directiva",
    "titulo": "[Directiva] Directiva General Código de Conducta Institucional del Servicio Nacional Forestal y de Fauna Silvestre – SERFOR - RGG N° D000039-2022-MIDAGRI-SERFOR.GG",
    "entidad": "SERFOR",
    "anio": 2022,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2022-11-18",
    "kb": 446.0,
    "archivo": "documentos/opr_19_directiva_general_codigo_de_conducta_institucional_del_documento.pdf",
    "original": "19_directiva_general_codigo_de_conducta_institucional_del_documento.pdf"
  },
  {
    "id": 99,
    "tipo": "Directiva",
    "titulo": "[Resolucion] Aprobar la Directiva General Nº d000001-2021-MIDAGRI-SERFOR-GG, “Ciclo de Vida del Software para el Servicio Nacional Forestal y de Fauna Silvestre - SERFOR” - RGG N° D0021-2021-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2021,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2021-06-24",
    "kb": 448.0,
    "archivo": "documentos/opr_22_aprobar_la_directiva_general_n_d000001_2021_midagri_ser_resolucion.pdf",
    "original": "22_aprobar_la_directiva_general_n_d000001_2021_midagri_ser_resolucion.pdf"
  },
  {
    "id": 100,
    "tipo": "Directiva",
    "titulo": "[Directiva] Aprobar la Directiva General Nº d000001-2021-MIDAGRI-SERFOR-GG, “Ciclo de Vida del Software para el Servicio Nacional Forestal y de Fauna Silvestre - SERFOR” - RGG N° D0021-2021-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2021,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2021-06-24",
    "kb": 1087.0,
    "archivo": "documentos/opr_22_aprobar_la_directiva_general_n_d000001_2021_midagri_ser_documento.pdf",
    "original": "22_aprobar_la_directiva_general_n_d000001_2021_midagri_ser_documento.pdf"
  },
  {
    "id": 101,
    "tipo": "Directiva",
    "titulo": "Aprobar la Directiva N° 001-2018-MINGARI-SERFOR-GG Directiva para la atención de Servicios Archivísticos en el archivo central del SERFOR - RGG Nº 0004-2018-MINAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2018,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2018-08-03",
    "kb": 3229.0,
    "archivo": "documentos/opr_25_aprobar_la_directiva_n_001_2018_mingari_serfor_gg_direc_resolucion.pdf",
    "original": "25_aprobar_la_directiva_n_001_2018_mingari_serfor_gg_direc_resolucion.pdf"
  },
  {
    "id": 102,
    "tipo": "Directiva",
    "titulo": "Aprobar la Directiva Nº 003-2016-SERFOR-SG Funcionamiento del Sistema Institucional de Archivos del SERFOR - RSG Nº 0017-2016-SERFOR-SG",
    "entidad": "SERFOR",
    "anio": 2016,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2016-06-06",
    "kb": 2747.0,
    "archivo": "documentos/opr_31_aprobar_la_directiva_n_003_2016_serfor_sg_funcionamient_resolucion.pdf",
    "original": "31_aprobar_la_directiva_n_003_2016_serfor_sg_funcionamient_resolucion.pdf"
  },
  {
    "id": 103,
    "tipo": "Directiva",
    "titulo": "[Resolucion] Aprobar la Directiva General N.º D000002-2023-MIDAGRI-SERFOR-GG “Directiva para la gestión de denuncias por presuntos actos de corrupción y otorgamiento de medidas de protección al/a la Denunciante en el Servicio Nacional Forestal y de Fauna Silvestre – SERFOR” - RGG N° D0003-2023-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-01-31",
    "kb": 313.0,
    "archivo": "documentos/opr_37_aprobar_la_directiva_general_n_d000002_2023_midagri_ser_resolucion.pdf",
    "original": "37_aprobar_la_directiva_general_n_d000002_2023_midagri_ser_resolucion.pdf"
  },
  {
    "id": 104,
    "tipo": "Directiva",
    "titulo": "[Directiva] Aprobar la Directiva General N.º D000002-2023-MIDAGRI-SERFOR-GG “Directiva para la gestión de denuncias por presuntos actos de corrupción y otorgamiento de medidas de protección al/a la Denunciante en el Servicio Nacional Forestal y de Fauna Silvestre – SERFOR” - RGG N° D0003-2023-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2023,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2023-01-31",
    "kb": 1019.0,
    "archivo": "documentos/opr_37_aprobar_la_directiva_general_n_d000002_2023_midagri_ser_documento.pdf",
    "original": "37_aprobar_la_directiva_general_n_d000002_2023_midagri_ser_documento.pdf"
  },
  {
    "id": 105,
    "tipo": "Directiva",
    "titulo": "[Resolucion] Directiva General N° D000002-2025-MIDAGRI-SERFOR-GG denominada \n“Directiva que regula la entrega y recepción de cargo de los/las Servidores/as \nCiviles del Servicio Nacional Forestal y de Fauna Silvestre – SERFOR - RGG N° D0000031-2025-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2025,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2025-03-04",
    "kb": 413.0,
    "archivo": "documentos/opr_39_directiva_general_n_d000002_2025_midagri_serfor_gg_deno_resolucion.pdf",
    "original": "39_directiva_general_n_d000002_2025_midagri_serfor_gg_deno_resolucion.pdf"
  },
  {
    "id": 106,
    "tipo": "Directiva",
    "titulo": "[Directiva] Directiva General N° D000002-2025-MIDAGRI-SERFOR-GG denominada \n“Directiva que regula la entrega y recepción de cargo de los/las Servidores/as \nCiviles del Servicio Nacional Forestal y de Fauna Silvestre – SERFOR - RGG N° D0000031-2025-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2025,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2025-03-04",
    "kb": 952.0,
    "archivo": "documentos/opr_39_directiva_general_n_d000002_2025_midagri_serfor_gg_deno_documento.pdf",
    "original": "39_directiva_general_n_d000002_2025_midagri_serfor_gg_deno_documento.pdf"
  },
  {
    "id": 107,
    "tipo": "Directiva",
    "titulo": "[Resolucion] Plan de Desarrollo de las Personas -PDP 2025 del Servicio Nacional Forestal y de Fauna Silvestre - SERFOR Y DOS MODIFICATORIAS - RGG N° D000034-2025-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2025,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": null,
    "kb": 356.0,
    "archivo": "documentos/opr_40_plan_de_desarrollo_de_las_personas_pdp_2025_del_servici_resolucion.pdf",
    "original": "40_plan_de_desarrollo_de_las_personas_pdp_2025_del_servici_resolucion.pdf"
  },
  {
    "id": 108,
    "tipo": "Directiva",
    "titulo": "[Directiva] Plan de Desarrollo de las Personas -PDP 2025 del Servicio Nacional Forestal y de Fauna Silvestre - SERFOR Y DOS MODIFICATORIAS - RGG N° D000034-2025-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2025,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": null,
    "kb": 263.0,
    "archivo": "documentos/opr_40_plan_de_desarrollo_de_las_personas_pdp_2025_del_servici_documento.pdf",
    "original": "40_plan_de_desarrollo_de_las_personas_pdp_2025_del_servici_documento.pdf"
  },
  {
    "id": 109,
    "tipo": "Directiva",
    "titulo": "[Resolucion] Aprobar la Directiva General N° D00004-2021-MIDAGRI-SERFOR-GG Gestión de la Información Espacial del Catastro Forestal - RGG N° D0024-2021-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2021,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2021-06-28",
    "kb": 387.0,
    "archivo": "documentos/opr_42_aprobar_la_directiva_general_n_d00004_2021_midagri_serf_resolucion.pdf",
    "original": "42_aprobar_la_directiva_general_n_d00004_2021_midagri_serf_resolucion.pdf"
  },
  {
    "id": 110,
    "tipo": "Directiva",
    "titulo": "[Directiva] Aprobar la Directiva General N° D00004-2021-MIDAGRI-SERFOR-GG Gestión de la Información Espacial del Catastro Forestal - RGG N° D0024-2021-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2021,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2021-06-28",
    "kb": 1974.0,
    "archivo": "documentos/opr_42_aprobar_la_directiva_general_n_d00004_2021_midagri_serf_documento.pdf",
    "original": "42_aprobar_la_directiva_general_n_d00004_2021_midagri_serf_documento.pdf"
  },
  {
    "id": 111,
    "tipo": "Directiva",
    "titulo": "Aprobar la Directiva General Nº D000002-2021-MIDAGRI-SERFOR-GG, denominada “Procedimiento Administrativo Disciplinario del Servicio Nacional Forestal y de Fauna Silvestre - SERFOR” - RGG N° D0022-2021-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2021,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2021-06-24",
    "kb": 416.0,
    "archivo": "documentos/opr_43_aprobar_la_directiva_general_n_d000002_2021_midagri_ser_resolucion.pdf",
    "original": "43_aprobar_la_directiva_general_n_d000002_2021_midagri_ser_resolucion.pdf"
  },
  {
    "id": 112,
    "tipo": "Directiva",
    "titulo": "[Resolucion] Aprobar la Actualización de la Directiva N° 002-2020-MINAGRI-SERFOR-GG Directiva de Gestión Documental del SERFOR - RGG Nº 0026-2022-MINAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2020,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2020-05-27",
    "kb": 347.0,
    "archivo": "documentos/opr_45_aprobar_la_actualizacion_de_la_directiva_n_002_2020_min_resolucion.pdf",
    "original": "45_aprobar_la_actualizacion_de_la_directiva_n_002_2020_min_resolucion.pdf"
  },
  {
    "id": 113,
    "tipo": "Directiva",
    "titulo": "[Directiva] Aprobar la Actualización de la Directiva N° 002-2020-MINAGRI-SERFOR-GG Directiva de Gestión Documental del SERFOR - RGG Nº 0026-2022-MINAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2020,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2020-05-27",
    "kb": 2634.0,
    "archivo": "documentos/opr_45_aprobar_la_actualizacion_de_la_directiva_n_002_2020_min_documento.pdf",
    "original": "45_aprobar_la_actualizacion_de_la_directiva_n_002_2020_min_documento.pdf"
  },
  {
    "id": 114,
    "tipo": "Directiva",
    "titulo": "“Directiva para la recepción, registro, canalización y seguimiento de denuncias vinculadas a infracciones y delitos en materia forestal y de fauna silvestre del Servicio Nacional Forestal y de Fauna Silvestre - SERFOR” - RGG N° D000026-2021-MIDAGRI-SERFOR-GG",
    "entidad": "SERFOR",
    "anio": 2024,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2024-10-09",
    "kb": 385.0,
    "archivo": "documentos/opr_64_directiva_para_la_recepcion_registro_canalizacion_y_seg_resolucion.pdf",
    "original": "64_directiva_para_la_recepcion_registro_canalizacion_y_seg_resolucion.pdf"
  },
  {
    "id": 115,
    "tipo": "Directiva",
    "titulo": "[Resolucion] Directiva para el control y supervisión del comercio Internacional de especies CITES - RDE N° D000239-2024-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2024,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2024-10-10",
    "kb": 388.0,
    "archivo": "documentos/opr_65_directiva_para_el_control_y_supervision_del_comercio_in_resolucion.pdf",
    "original": "65_directiva_para_el_control_y_supervision_del_comercio_in_resolucion.pdf"
  },
  {
    "id": 116,
    "tipo": "Directiva",
    "titulo": "[Directiva] Directiva para el control y supervisión del comercio Internacional de especies CITES - RDE N° D000239-2024-MIDAGRI-SERFOR-DE",
    "entidad": "SERFOR",
    "anio": 2024,
    "estado": "Vigente",
    "coleccion": "Lineamientos y Directivas OPR",
    "fecha": "2024-10-10",
    "kb": 1856.0,
    "archivo": "documentos/opr_65_directiva_para_el_control_y_supervision_del_comercio_in_documento.pdf",
    "original": "65_directiva_para_el_control_y_supervision_del_comercio_in_documento.pdf"
  }
];
